# Define your Python environment (conda)
name: default
channels:
  # Where to download dependencies from
  - conda-forge
dependencies:
  # Choose your Python version
  - python=3.9
  - pip
  - pip:
    # List all your Python dependencies
    - pandas
